package Vue;

public enum EventType {
	JOUER_TOUR,
	FIN_PARTIE,
	DEBUT_MANCHE,
	
	CHOIX_JOUEUR_JVIRTUEL,
	CHOIX_INGREDIENT_JVIRTUEL,
	CHOIX_EMPLACEMENT_JVIRTUEL,
	CHOIX_DEBUT_JVIRTUEL,
	
	AFFICHAGE_LISTE_JOUEUR,
	AFFICHAGE_INGREDIENT,
	AFFICHAGE_ALLIE,
	
	ACTION_GEANT,
	ACTION_ENGRAIS,
	ACTION_FARFADET,
	ACTION_TAUPE
}
